name: Automated Knit

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  knit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v1

    - name: Install Pandoc
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.14.2/pandoc-2.14.2-linux-amd64.tar.gz
        tar xvzf pandoc-2.14.2-linux-amd64.tar.gz
        sudo cp pandoc-2.14.2/bin/pandoc /usr/local/bin/

    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("rmarkdown"))'

    - name: Print System Information
      run: Rscript -e "install.packages('sysinfo'); sysinfo::sys_info()"

    - name: Knit the RMarkdown file
      run: |
        Rscript -e 'rmarkdown::render("automate_knit/update.Rmd")'

    - name: Commit and push changes
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your.email@example.com"
        git add automate_knit/update.md
        git commit -m "Automated Knit Update $(date -u +%Y-%m-%d)"
        git push origin main
